[env:esp32-s3-poe] 
extends = esp32s3_base
board = 4d_systems_esp32s3_gen4_r8n16
board_level = pr
board_check = true
build_flags = 
  ${esp32s3_base.build_flags}
  -D PRIVATE_HW
  -I variants/esp32s3/diy/esp32-s3-poe

lib_ignore =
  Ethernet

lib_deps = 
  ${esp32s3_base.lib_deps}
  https://github.com/meshtastic/ETHClass2/archive/v1.0.0.zip
