[env:esp32-s3-poe] 
extends = esp32s3_base
board = 4d_systems_esp32s3_gen4_r8n16
board_upload.flash_size = 16MB
board_build.partitions = partition-table-16MB-no-ota.csv
custom_webui_dir = variants/esp32s3/diy/esp32-s3-poe/webui
board_level = pr
board_check = true
extra_scripts =
  ${env.extra_scripts}
  pre:variants/esp32s3/diy/esp32-s3-poe/webui_buildfs.py
build_flags = 
  ${esp32s3_base.build_flags}
  -D PRIVATE_HW
  -I variants/esp32s3/diy/esp32-s3-poe

lib_ignore =
  Ethernet

lib_deps = 
  ${esp32s3_base.lib_deps}
  https://github.com/meshtastic/ETHClass2/archive/v1.0.0.zip
